# Generated by Django 4.2.3 on 2023-08-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Author', models.CharField(max_length=100)),
                ('email', models.EmailField(default='nahidkalam@gmail.com', max_length=254)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.webpage')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessRecords',
        ),
    ]
